[project]
name = "airflow-training-udemy"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "airflow-stubs>=0.0.1",
    "apache-airflow>=2.10.5",
    "black>=25.1.0",
    "isort>=6.0.1",
]
